token_regex = r'[^a-z0-9]+'
infobox_regex = r"{{ ?infobox(?:.|\n)*?\n}}"
ignore_ref_regex = r"(< ?ref[^/>]*/>)"
reference_regex = r"(< ?ref([^>])*>.*?</ref>)"
category_regex = r"\[\[.*category.*?\]\]"
links_regex = r"==.*external links.*==|==.*links.*=="
garbage_regex = r"([0-9]+[a-z]+[0-9a-z]+)|([a-z]+[0-9]+[0-9a-z]+)|(\d{4}\d+)"
http_regex = r"https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)"

FILE_TERM_SIZE = 30000

extra_stop_words = ["didn't", 'mr', 'looking', 'ours', 'beyond', 'refs', 'little', 'perhaps', 'as',
                    'keep', 'ig', 'despite', 'hi', 'aj', 'lr', 'cz', 'seeming', 'theyd', 'gi', 'im',
                    'begins', 'wo', 'pc', 'second', 'considering', 'better', 'si', 'gs', 'po',
                    'thats', 'actually', 'him', 'different', 'eq', 'importance', 'ma', 'yj',
                    'associated', 'le', 'ba', 'thin', 'itself', "that's", 'xt', 'needs', "we've",
                    'let', 'forth', 'etc', 'x1', 'within', 'thence', "that'll", 'how', 'next',
                    'les', 'ot', 'i3', 'related', "t's", 'potentially', 'used', 'look', 'fs',
                    'usefulness', 'mostly', 'js', 'ro', 't1', 'xn', 'aren', 'six', 'strongly', 'mo',
                    'mill', 'thru', 'think', 'keeps', 'new', 'p', "he'll", 'mine', 'par',
                    "mightn't", 'en', 'somewhat', 'contain', 'pm', 'shouldn', 'unfortunately',
                    'indicated', 'myself', 'inc', 'get', 'asking', 'um', 'far', 'sincere',
                    'appreciate', 'all', 'ts', 'el', 'os', 'bs', 'serious', 'end', 'went', 'noone',
                    "wasn't", 'vq', 'saying', 'ok', "there's", 'neither', 'certainly', 'most',
                    'nevertheless', 'fa', 'et-al', 'ix', 'thoroughly', 'latterly', 'yr', 'likely',
                    'full', 'enough', 'information', 'much', 'se', 'to', 'believe', 'hereby',
                    'novel', 'il', 'xx', 'yes', 'vols', 'edu', 'u201d', 'cause', 'resulted', 'both',
                    'nj', 'date', "couldn't", "hadn't", 'certain', 'ex', 'ap', 'ri', 'going', 'hj',
                    'volumtype', 'og', 'lb', 'showed', 'ra', 'later', 'see', 'some', 'isn',
                    'elsewhere', 'onto', 'lo', 'come', 'ep', 'gy', 'every', 'ax', 'somewhere',
                    'hers', 'ltd', 'ca', 'gets', 'rf', 'were', 'same', 'them', 'rn', 'resulting',
                    'unlike', 'indicates', 'ir', 'because', 'regardless', 'dt', 'containing',
                    'none', 'b1', 'therefore', "she's", 'did', 'e3', 'about', 'this', 'is', 'r',
                    'immediately', 'allow', "there've", 'dl', 'there', "won't", 'sometime', 'eo',
                    'ni', 'sufficiently', 'downwards', 'ref', 'according', 'iv', 'didn', 'va', 'i7',
                    'like', 'describe', 'rc', 'inward', 'cf', 'r2', 'abst', 'being', 'xl', 'me',
                    'sup', 'of', 'iz', 'cit', 'seem', 'important', 'de', 'provides', 'may',
                    'willing', 'got', 'trying', 'into', 'cc', 'shes', 'mainly', 'thereafter',
                    'research', 'right', 'giving', 'hy', 'have', 'dp', 'az', 'be', 'whom', 't2',
                    'secondly', 'back', '0s', 'hundred', 's', 'whereas', 'either', 'say', 'give',
                    'do', 'inasmuch', 'thick', 'hid', 'together', 'significantly', 'apparently',
                    'necessary', 'thou', 'behind', 'com', 'almost', 'begin', 'nine', 'hopefully',
                    'announce', 'h3', 'whomever', 'est', 'bd', 'truly', 'www', 'youd', 'really',
                    'interest', 'tn', 'f2', 'around', 'soon', 'pu', 'instead', 'its', 'ke',
                    'former', 'mean', 'lest', 'tm', "c'mon", 'tl', 'am', 'oa', 'sy', "you'll", 'rv',
                    'm', 'con', 'show', "they'll", 'wherein', 'pk', 'please', 'theyre', 'greetings',
                    'lets', 'maybe', 'least', 'au', 'rd', 'obtain', 'besides', 'than', 'except',
                    'l2', 'yourself', 'fl', 'tell', 'came', 'ec', 'uk', 'comes', 'now', 'i8',
                    'just', 'follows', 'predominantly', 'lately', 'ys', "mustn't", 'sz', 'thereof',
                    'y2', 'does', 'obtained', 'cy', 'seriously', 'fn', 'ef', 'couldnt', "weren't",
                    'plus', 'mug', 'u', 'nobody', 'tq', 'hh', 'ee', 'cm', 'fire', 'latter', 'pn',
                    'ge', 'way', 'substantially', 'xo', 'sf', 'bp', 'twice', 'yl', 'top', '0o',
                    'c2', 're', 'formerly', "i'd", 'ob', 'hr', "shouldn't", 'df', 'became',
                    'eleven', 'must', 'need', 'sm', 'yours', 'two', 'gone', 'detail', 'said',
                    'across', 'thanks', 'self', 'moreover', 'xj', 'our', 'thickv', 'successfully',
                    'los', 'cl', 'fu', 'bu', 'du', 'those', 'vd', 'several', 'slightly', 'first',
                    'whatever', 'consequently', 'thereby', 'toward', 'four', 'clearly', 'q', 'z',
                    'ds', 'cant', 'ibid', 'cu', 'ib', 'tb', 'ou', 'hu', 'ic', 'given', 'ae',
                    'hardly', 'has', 'wish', 'pr', 'system', 'below', 'showns', 'uses', "it'll",
                    'his', 'e', 'ci', 'nearly', 'rl', "it's", 'nr', 'amoungst', 'zz', '3a', 'l',
                    'beforehand', 'wouldnt', 'one', 'similarly', 'thereto', 'indeed', 'd2', 'qj',
                    'act', 'es', 'twenty', 'fy', 'pq', 'a2', 'though', 'done', 'gl', 'section',
                    'otherwise', 'when', 'whither', "she'll", 'are', 'beside', 'himself', 'okay',
                    'oh', 'concerning', 'un', 'fifteen', 'seen', 'specifying', 'lt', 'via', 'a3',
                    'cg', 'ff', 'alone', 'av', 'take', 'o', 'c1', 'million', 'fo', 'aside', 'by',
                    'ce', 'lf', "i'll", 'io', 'bj', 'won', 'reasonably', 'fj', "doesn't", 'causes',
                    'needn', 'cp', 'else', 'put', 'iq', 'lc', 'shall', '6o', 'seemed', 'rm', 'ss',
                    'w', 'selves', 'e2', 'nc', 'p1', 'vj', 'consider', 'ch', 'sq', 'biol', '3d',
                    'allows', 'weren', 'cs', "he'd", 'bl', 'regarding', 'approximately', 'herself',
                    'cry', 'wa', 'til', "c's", 'kept', 'a1', 'tends', 'nos', 'x', 'b', 'eighty',
                    'ps', 'ac', 'seeing', 'co', 'following', 'itd', 'whereupon', 'specified', 'tr',
                    'al', 'example', 'x2', 'b2', 'ie', 'sorry', 'y', 'best', 'rather', 'becomes',
                    'ay', 'ry', 'even', 'adj', 'therein', "they'd", 'tip', 'last', 'pj', 'shan',
                    'not', 'mightn', 've', 'briefly', 'something', 'able', 'bk', 'affects', 'from',
                    't3', 'sure', 'ia', 'anyone', 'ui', 'oz', 'throughout', 'pas', 'before', 'em',
                    'ip', 'yourselves', 'their', 'affecting', 'try', 'so', 'bottom', 'for', 'sp',
                    'mt', 'thoughh', 'outside', 'will', 'promptly', 'oq', 'dr', 'against', 'pe',
                    "there'll", 'old', 'nor', 'mu', "you've", 'an', "wouldn't", 'it', 'cd', 'kj',
                    'thereupon', 'hither', 'your', 'nay', 'anywhere', 'once', 'become', 'described',
                    'still', 'until', 'and', 'iy', 'bt', 'currently', 'rj', 'dx', 'per', 'followed',
                    'over', 'five', 'thorough', 'since', 'haven', "they've", 'very', 'specifically',
                    'ain', 'cr', 'appear', 'us', 'on', 'tt', 'whats', 'poorly', 'but', '3b', 'only',
                    "don't", 'ut', 'made', 'up', 'aw', 'whoever', 'rt', 'i2', 'help', 'hes', 'jj',
                    'more', 'wouldn', 'at', 'index', 'her', 'bill', 'ey', 'the', 'doesn', 'xk',
                    "i've", 'becoming', 'any', 'cj', 'g', 'h', 'that', 'youre', 'everywhere',
                    "she'd", 'te', 'cq', 'somehow', 'ii', 'hereafter', "where's", 'rs', 'cn', 'ab',
                    'makes', 'contains', 'ct', 'ur', 'among', 'usefully', 'third', 'anymore', 'tf',
                    'particularly', 'werent', 'why', 'happens', 'previously', 'rq', 'shows', 'qv',
                    'during', 'proud', 'tc', 'after', 'apart', 'beginnings', 'j', 'sn', 'url',
                    'liked', "we're", 'necessarily', 'then', 'ln', 'eu', 'ls', 'yt', 'ow', 'shed',
                    'theirs', 'oc', 'should', 'anyways', 'you', 'appropriate', 'sensible', 'zi',
                    'tx', 'sa', 'k', 'largely', 'ns', 'immediate', 'awfully', 'go', 'normally',
                    'words', 'if', 'th', '6b', 'uj', 'whereby', 'others', 'whenever', 'c3', 'ml',
                    'oi', 'kg', "here's", 'br', 'et', 'xf', 'herein', 'affected', 'ho', 'amongst',
                    'tried', 'ei', 'ones', 'was', 'means', 'whole', 'hs', 'ag', 'p2', 'ue', 'thank',
                    'zero', 'll', 'namely', 'possibly', 'primarily', 'without', "they're", 'x3',
                    'too', 'had', 'other', 'fill', 'looks', 'definitely', 'away', 'oj', 'similar',
                    'call', 'pd', 'insofar', 'know', 'b3', 'di', 'using', 'overall', 'line', 'home',
                    'welcome', 'pf', 'st', 'rh', 't', "that've", 'down', 'throug', 'ask',
                    'presumably', "he's", 'unlikely', 'move', 'stop', 'saw', 'whereafter', 'wed',
                    'ran', 'cannot', 'jt', 'fifth', 'significant', 'regards', 'rr', 'ij', 'therere',
                    'n', 'non', 'xi', 'ms', 'value', 'less', 'd', 'pp', 'whether', 'three',
                    'obviously', 'qu', 'arent', 'lj', 'past', 'ed', 'thered', 'changes', 'known',
                    'off', 'vo', 'mustn', 'uo', 'again', 'invention', 'while', 'somethan', 'these',
                    'dd', 'arise', 'mrs', 'bc', 'vs', 'a4', 'ko', 'merely', 'sl', 'i4', 'ten',
                    'ninety', 'sometimes', 'ad', "what'll", 'nothing', 'ju', "who'll", 'what',
                    'placed', 'i', 'nonetheless', 'anyhow', 'que', 'wants', "why's", 'v', 'da',
                    "i'm", 'between', 'whence', 'however', 'anybody', 'widely', 'we', 'er', 'sj',
                    'also', 'well', 'wasn', "shan't", 'course', 'particular', 'unto', 'howbeit',
                    "ain't", 'miss', 'afterwards', 'km', 'dk', 'probably', 'eg', "it'd", 'thanx',
                    'entirely', 'never', 'ng', 'a', 'thousand', 'hereupon', 'nn', 'seven', 'yet',
                    'https', 'noted', "we'll", 'part', 'ord', 'whos', 'out', 'relatively', 'above',
                    'everybody', 'took', 'wont', 'hence', 'would', 'om', 'ox', 'well-b', 'might',
                    'i6', 'ej', 'la', 'he', 'od', 'ft', 'own', 'furthermore', 'pt', 'gave', 'n2',
                    'whod', 'vu', 'ph', "should've", 'who', "needn't", "you'd", 'everything',
                    'accordance', 'or', 'tj', 'goes', 'nt', 'nowhere', 'exactly', 'gj',
                    'themselves', 'hello', 'bx', 'xs', 'use', 'taken', 'id', 'nl', 'tp', 'mg',
                    'eight', 'towards', 'found', 'could', 'ah', 'where', 'near', 'tries', 'effect',
                    'someone', 'specify', 'ar', "what's", 'anything', 'recently', 'another', 'nd',
                    'few', "aren't", 'meanwhile', 'td', 'c', 'dc', 'can', "isn't", 'ought', 'na',
                    "we'd", 'already', "when's", 'wonder', 'available', 'sc', 'unless', 'viz', 's2',
                    'don', 'bi', 'respectively', 'everyone', 'theres', 'inner', 'twelve', 'anyway',
                    'ru', 'sec', 'ourselves', 'wi', 'm2', 'oo', "a's", 'doing', 'op', 'sr', 'want',
                    'somebody', 'various', 'in', 'fify', "you're", 'ne', 'pages', 'says', 'vol',
                    'run', 'dj', "can't", 'added', 'ti', 'although', 'f', 'she', 'h2', 'mn', 'ol',
                    'often', 'make', 'ny', 'owing', 'useful', 'side', 'af', 'wheres', 'quite', 'no',
                    'gives', 'hadn', 'fc', 'fix', 'ev', "haven't", 'many', 'taking', 'jr', 'ending',
                    "let's", 'ea', 'world', 'p3', 'heres', 'corresponding', 'sub', 'tv', 'ever',
                    'seems', 'they', 'py', 'hed', 'ih', 'ga', 'wherever', 'thus', 'been', 'sent',
                    'suggest', 'pl', 'especially', 'possible', 'couldn', 'cx', 'due', 'always',
                    'getting', 'cv', 'find', 'gr', 'usually', 'xv', 'pi', 'vt', 'ignored', 'http',
                    'each', 'along', 'under', 'my', 'upon', 'gotten', 'fr', 'hasnt', 'front',
                    'which', 'whose', 'through', 'meantime', 'auth', 'dy', 'ao', 'readily', 'such',
                    'whim', 'bn', 'sd', 'wasnt', 'results', 'here', 'omitted', "who's", 'ups',
                    'name', 'further', 'fi', 'with', 'forty', "hasn't", "how's", 'recent',
                    'present', 'shown', 'accordingly', 'fifty', 'hasn', 'indicate', 'having',
                    'knows']
